basePath: /api/v1
definitions:
  example_pesto-backend_internal_models.ClipboardItem:
    description: A clipboard item with its content and metadata
    properties:
      content:
        description: Content of the clipboard item
        example: Hello, world!
        type: string
      content_type:
        description: Type of the content (e.g., text, image, url)
        example: text
        type: string
      created_at:
        description: Creation timestamp
        example: "2025-01-01T00:00:00Z"
        type: string
      deleted_at:
        description: Deletion timestamp (if deleted)
        example: "null"
        type: string
      id:
        description: ID of the clipboard item
        example: 1
        type: integer
      is_current:
        description: Whether this is the current clipboard item
        example: true
        type: boolean
      updated_at:
        description: Last update timestamp
        example: "2025-01-01T00:00:00Z"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A clipboard manager API with automatic monitoring
  title: Pesto Clipboard API
  version: "1.0"
paths:
  /clipboard-items:
    get:
      consumes:
      - application/json
      description: Get all clipboard items ordered by creation time
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/example_pesto-backend_internal_models.ClipboardItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all clipboard items
      tags:
      - clipboard
    post:
      consumes:
      - application/json
      description: Create a new clipboard item
      parameters:
      - description: Clipboard Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/example_pesto-backend_internal_models.ClipboardItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/example_pesto-backend_internal_models.ClipboardItem'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new clipboard item
      tags:
      - clipboard
  /clipboard-items/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a clipboard item by its ID
      parameters:
      - description: Clipboard Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a clipboard item
      tags:
      - clipboard
    get:
      consumes:
      - application/json
      description: Get a specific clipboard item by its ID
      parameters:
      - description: Clipboard Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/example_pesto-backend_internal_models.ClipboardItem'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a clipboard item by ID
      tags:
      - clipboard
  /clipboard-items/content/{content_type}:
    get:
      consumes:
      - application/json
      description: Get all clipboard items with a specific content type
      parameters:
      - description: Content Type
        in: path
        name: content_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/example_pesto-backend_internal_models.ClipboardItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get clipboard items by content type
      tags:
      - clipboard
  /clipboard-items/current:
    get:
      consumes:
      - application/json
      description: Get the current clipboard item (the most recently copied item)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/example_pesto-backend_internal_models.ClipboardItem'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get the current clipboard item
      tags:
      - clipboard
swagger: "2.0"
